---
abstract: 'A reader for Build.PL configuration files'
author:
  - 'Leon Timmermans <fawaka@gmail.com>'
build_requires:
  Cwd: 0
  Test::Differences: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-BuildRC
requires:
  Carp: 0
  Exporter: 5.57
  File::Spec::Functions: 0
  Text::ParseWords: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=ExtUtils-BuildRC
  repository: git://github.com/Leont/extutils-buildrc.git
version: 0.001
